settings:
  title: '状态页 | 云探针'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统都在运行'
  notAllmonitorsOperational: '并非所有系统都在运行'
  monitorLabelOperational: '运行正常'
  monitorLabelNotOperational: '运行异常'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 次运行异常' # xx incident(s) recorded

monitors:
  - id: gh-pages # unique identifier
    name: Github Pages
    description: 'Github Pages' # default=empty
    url: 'https://worldhim.github.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: oneindex
    name: OneIndex
    description: 'OneIndex'
    url: 'https://oneindex-worldhim.vercel.app/'
    method: GET
    expectStatus: 200
    followRedirct: false 
    linkable: true 

  - id: onemanager
    name: OneManager
    description: 'OneManager'
    url: 'https://onemanager.worldhim.repl.co/'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: true 
    
  - id: docs
    name: Docs
    description: 'Powered by Docsify'
    url: 'https://docs-worldhim.vercel.app/'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: true 
