settings:
  title: '状态页 | 云探针'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: worldhim-github-io # unique identifier
    name: worldhim.github.io
    description: 'Github Pages' # default=empty
    url: 'https://worldhim.github.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: oneindex
    name: OneIndex
    description: 'OneIndex'
    url: 'https://worldhim-oneindex.vercel.app/'
    method: GET
    expectStatus: 200
    followRedirct: false 
    linkable: true 

  - id: onemanager
    name: OneManager
    description: 'OneManager'
    url: 'https://onemanager.worldhim.repl.co/'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: true 
